### ISSUE TITLE
iLvl not going to the maximum for the chaos recipe

### ISSUE THREAD

**Issue by viper949** [notablackbear/poe_qolV2#14]
Hello I was testing your tool some more (it's GREAT!) but something I noticed is that the chaos recipe uses items from 60-74 but your tool seems to cut off the iLvl before then. I have an example below:

Everything in this picture is iLvl 70:
![image](https://user-images.githubusercontent.com/16552046/93400506-c9738380-f834-11ea-81e9-d9f1ca7f101f.png)

If I drop a iLvl 63 helm as well it does show up:
![image](https://user-images.githubusercontent.com/16552046/93400575-f0ca5080-f834-11ea-8d25-30ed719f71c2.png)

But if I hold alt you can see I have an iLvl 71 and 74 helm on the ground as well that are not showing with the filter:
![image](https://user-images.githubusercontent.com/16552046/93400755-62a29a00-f835-11ea-8025-ecaee6a098cd.png)

**Comment by notablackbear** [comment]
Yes, the lowest item level should be 60, and highest should be 74. I will fix that.

I am not sure why the helmet isn't showing up, unless you changed the `threshold` in your `Setup.ini` file.

**Comment by notablackbear** [comment]
Fixed with V2.0.3
