### ISSUE TITLE
"Failed to execute script POE_QOL2" error because non-ASCII account name

### ISSUE THREAD

**Issue by albertojnk** [notablackbear/poe_qolV2#15]
Hi there, hope I can get some help here.

OS: Windows 10 (I'm in Windows Insider Program)
![image](https://user-images.githubusercontent.com/28850899/93402674-cd66cc00-f85b-11ea-8a9e-bb00972e327c.png)

Resolution: (both monitors)
![image](https://user-images.githubusercontent.com/28850899/93402968-97761780-f85c-11ea-82cb-25dea1067cc5.png)

POE filter folder:
- C:\Users\albertojnk\Documents\My Games\Path of Exile

Simulating the error:

- Download poe_qolV2 from release tag v0.2.2
- Extract all files to a folder in desktop
- Added my account name & POESESSID
- changed threshhold to 10 (also happens without changing)

In Matth's video, he said this error is related to either Resolution or Filter problems, so I guess I have a problem with my filters or any problems detecting my resolution because I have 2 monitors?!?

**Comment by trentwv** [comment]
so, i have this issue if i don't delete the filter in my documents.  once i delete the filter and allow the program to create it from the filter in the prog folder it works fine.

**Comment by albertojnk** [comment]
I just discovered something.

My account has a  non-ASCII/UTF-8 charactere - account: `GolpeBaixØ` - and I has using https://www.urlencoder.org/ to encode it which resulted in `GolpeBaix%C3%98`, just like it automaticly encode in PoB:

PoB: 
![image](https://user-images.githubusercontent.com/28850899/93409696-cf398b00-f86d-11ea-9a4f-337f60abfab5.png)

Since my account has a non-ASCII/UTF-8 charactere, I've created a new account to test if the problem was account related and turns out it is account related.

With my new account `albertojnk` it runs like a charm.

I Hope this bug can be fixed until leaguestart because if it happens to me it will probably happens to other ppl with account names like this.

**Comment by notablackbear** [comment]
Hi. yes this is a known issue in #11. Unfortunately I am not going to be able to fix by league start. I'd recommend combining [stashvision](https://youtu.be/SpQMNooprP4) with [chaos-recipe-overlay](https://github.com/exile-center/chaos-recipe-overlay) for a similar highlight/item counter tool in the mean time.
