### ISSUE TITLE
filters directory with encoder 

### ISSUE THREAD

**Issue by Perplex29** [notablackbear/poe_qolV2#19]
My filters directory has non-ASCII characters, can you expand the same encoder you did for the name also for the URL?
If I make a different directory without non-ASCII chars it works. But I can't change the Filter folder directory as well as I can't change my user folder name.

**Comment by notablackbear** [comment]
Please try the latest release and let me know if there is still an issue.

**Comment by Perplex29** [comment]
Works fine now. Thank you for the effort.
