### ISSUE TITLE
bug?

### ISSUE THREAD

**Issue by SeanIsHappy** [notablackbear/poe_qolV2#2]
![2020-09-16 17_07_40-Awakened PoE Trade](https://user-images.githubusercontent.com/66193244/93316742-2e33db80-f83f-11ea-80b8-6f51290308ee.png)

it is not counting properly

**Comment by notablackbear** [comment]
It will only highlight unidentified item sets. The second number (in your screen shot, the '6' in the gray overlay box) is how many identified rares it detects, which is a left over "feature". It is less than half as efficient to do the identified rare chaos recipe, so we don't highlight it. 

I'll add a note to the Readme.

Add a full, unitentified set to your stash and give it a try and let me know if that works.

**Comment by SeanIsHappy** [comment]
ok thanks

> It will only highlight unidentified item sets. The second number (in your screen shot, the '6' in the gray overlay box) is how many identified rares it detects, which is a left over "feature". It is less than half as efficient to do the identified rare chaos recipe, so we don't highlight it.
> 
> I'll add a note to the Readme.
> 
> Add a full, unitentified set to your stash and give it a try and let me know if that works.

ok thanks 👍
