### ISSUE TITLE
Fatal error detected

### ISSUE THREAD

**Issue by cristianocps** [notablackbear/poe_qolV2#20]
After configuring the app as described in the repo, just got the error in the screenshot below.
Someone got the same error solved?

Thanks in advance
![image](https://user-images.githubusercontent.com/11409684/93526604-10817780-f90e-11ea-9109-c299439f46ad.png)

**Comment by notablackbear** [comment]
Please try the latest release and see if that fixes the issue. There is also some new, limited logging functionality that can be enabled if there is still an issue.
