### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by Deannnnnnn** [notablackbear/poe_qolV2#22]
I set it up following https://www.youtube.com/watch?v=_gSOBcYedok&ab_&ab_channel=PathofMatth but still got a fatal error
Anyone got the same error and solved it ? 
![Screenshot_2](https://user-images.githubusercontent.com/56488043/93546862-130ebc00-f964-11ea-9c3b-58d7bafca3c3.png)

**Comment by notablackbear** [comment]
Hi please use the latest release [here](https://github.com/notablackbear/poe_qolV2/releases/tag/V2.0.3) and please read everything
