### ISSUE TITLE
Chaos Recipe button disagrees with the overlay

### ISSUE THREAD

**Issue by naamaloomi** [notablackbear/poe_qolV2#23]
According to the overlay I have enough items for 2x chaos recipe, but when pressing the "Chaos Recipe" it says "Not enough Chaos Recipe items".

![image](https://user-images.githubusercontent.com/395402/93599086-df608000-f9bd-11ea-9abf-0f6db40b1428.png)

Update:
Using version 2.0.3

**Comment by notablackbear** [comment]
The tool only works with unidentified items, where as the numbers to the right are counting the identified items. The id chaos recipe is 50% less efficient. We may add option to enable later, but don't want to encourage it right now.
