### ISSUE TITLE
Default chaos filter starts at 65, should be 60

### ISSUE THREAD

**Issue by RuneBarrett** [notablackbear/poe_qolV2#25]
The default chaos_items_filter.filter is only showing items from ilvl 65 and upwards. The chaos recipe starts at ilvl 60 and Blood Aqueduct is lvl61.
Thanks for reviving this! great tool

**Comment by notablackbear** [comment]
this is fixed and will be included in the next release (fixed in the v2.0.3 pre-release availiable now)
