### ISSUE TITLE
Filter Reseting

### ISSUE THREAD

**Issue by arkanjompf** [notablackbear/poe_qolV2#28]
when i reload the filter through UI the filter starts showing all items, as if there was no filter

**Comment by abdukulov-talgat** [comment]
same

**Comment by Tonkan92** [comment]
Same, can't for the life of me figure out what is wrong

**Comment by abdukulov-talgat** [comment]
found solution and problem.

> #### Below is the filter that will be added to your filters if it is not already there, and will update as needed.
#### This is still under development, so if you want to use this feature, make a copy of the provided filter and edit it to your preferences
#### The app will read, update, and then save an updated filter to your filters directory ("Documents\My Games\Path of Exile").
#### Right now it depends on finding 234hn50987sd to know when the chaos recipe section starts and looks for 2345ina8dsf7 to know what line it stops at. 5head, I know.
#### So if you want to use your own filter, I can't guarantee anything. My best advice would be to look at the provided filter and where the chaos recipe is inserted and try to duplicate that in your own filter. Then put that custom filter into this directory and change the name below.

U need to add in to your filter chaos section from standart filter (copy-paste)

**Comment by notablackbear** [comment]
related to #34 also
