### ISSUE TITLE
One hand weapons not turning off at threshold

### ISSUE THREAD

**Issue by bubba42124** [notablackbear/poe_qolV2#3]
Amazing tool.  All other item types are correctly turning off when i update the filter but one hand weapons are still showing.  Multiple updates of both the refresh button and filter in several new game instances.  To test I have 4 sets of chaos recipe as my threshold and everything else turned off correctly at 4.  Weapons passed 8 and is now about 20 and still not turning off when i update the filter.

**Comment by notablackbear** [comment]
Please re-download the latest exe and try that (and the chaos_item_filter.filter file which has also been updated)
