### ISSUE TITLE
Side win taskbar ruins recipe highlight

### ISSUE THREAD

**Issue by Zeplo103** [notablackbear/poe_qolV2#31]
![image](https://user-images.githubusercontent.com/50031857/93663235-ed220e00-fa6e-11ea-92c8-ae1b5aa34ea1.png)

**Comment by Zeplo103** [comment]
resolution was set to the window's custom

**Comment by notablackbear** [comment]
The highlights are based on the top left pixel being 0,0. This isn't something that can easily be fixed unfortunately
