### ISSUE TITLE
Please fix the Pernarch Typo

### ISSUE THREAD

**Issue by Ashon95** [notablackbear/poe_qolV2#34]
Please fix the Pernarch Typo

**Comment by sclient** [comment]
If someone could update the filter on Filterblade, that would be really helpful!

**Comment by eljoey** [comment]
In the POEQOL_Base filter thats in the folder. Change the "Pernarch" to "Pernach" then delete the POEQOL_Base filter that is in your mygames/poe folder and it should not have errors when you update

**Comment by notablackbear** [comment]
Thanks for doing the manual edits. Since Neversink made updates they will make it here soon
