### ISSUE TITLE
Detected threat: Trojan:Win32/Wacatac.DD!m

### ISSUE THREAD

**Issue by LootLary** [notablackbear/poe_qolV2#44]
Win defender found a trojan in the POE_QOL2.exe im not sure if other people got it too. I dont know what to do more then uninstalling and remove all data sadly there is no way to use this tool anymore. help or suggestions would be super nice ty!

**Comment by mershedpaderder** [comment]
I have just received this as well. Was working yesterday.

**Comment by LootLary** [comment]
i tryed 3 older versions too but always the same. but im using it since friday and  all works fine until now

**Comment by notablackbear** [comment]
You can run the file through a virus checker. Windows is giving some people false positives, which happens often with python scripts.

https://www.virustotal.com/gui/file/fbf374c0928eb5d53bb22fea94be2926d3f6c355bed657ea3ed7e4aca4af306f/detection
