### ISSUE TITLE
Filter not updating as it should logically do

### ISSUE THREAD

**Issue by himmls** [notablackbear/poe_qolV2#48]
When modifying the POEQOL_Base.filter in the application's directory to example also show Blacksmith Whetstone or Armourer Scraps I expected it to take those values to dynamically update the filter in the Path of Exile filter directory when hitting refresh, but it keeps just overwriting those custom made changes and takes a clean preset from somewhere else?
So the filter in the app directory is just for copy & paste purposes?
I even tried to put my changes in the "chaos_items_filter.filter" file, but there they also don't get inserted when hitting refresh.
Just confusing for me is that when renaming the "Pernarch" to "Pernach" in the filter located in the app directory it also fixed it in the updated filter from POE I think, so what exactly gets overwritten by some default values coming from anywhere not editable?
Also this custom change to "Pernarch" does not get overwritten on refreshing, currency changes somehow do.
Both changes are outside the scope of "234hn50987sd" and "2345ina8dsf7", so why resetting those values? 
Makes custom filter settings nearly impossible...

Any idea on how to do such changes more easily or am I overseeing things??

**Comment by rainingpaper** [comment]
Is some how where u put the 234hn50987sd/2345ina8dsf7 in a different spot that the default filter uses? that could be a possible issue.

**Comment by himmls** [comment]
Nah, using the default filter just with the removed "Pernarch" textline.
DId not move anything in the filter file.
But am I correct that the refresh function does not use the default filter file in the app directory and just rewrites the default values?
Would be strange to me, since using the default filter file and just switching the spot with the "chaos_items_filter.filter" entries would make most sense. So people would be able to make adjustments to the file and not losing changes.

**Comment by rainingpaper** [comment]
Far as I can tell it only works on the filter that u input in the same folder as the .exe.  It should only write over the things in the middle of the defining strings.  The filter that was left with the download I believe was for previous league so some of the changes aren't implimited for this league.  I just did a download of a new one from filterblade and took the section with the defining strings and copied it over and haven't had appeared to have any real issues.

**Comment by notablackbear** [comment]
> When modifying the POEQOL_Base.filter in the application's directory to example also show Blacksmith Whetstone or Armourer Scraps

Only Chaos Recipe items are considered. It won't track any random item, and is not intended to. You are welcome to try and implement this, but its not the focus of the project. I'd be happy to consider a pull request.
