### ISSUE TITLE
error "Failed to execute script POE_QOL2"

### ISSUE THREAD

**Issue by LoneWolfHowl** [notablackbear/poe_qolV2#5]
Hi,
I am running into an error "Failed to execute script POE_QOL2".

I have tried setting up the settings.ini in various ways. I have the correct account, PoE Session ID, league, monitor resolution and tab index.

I suspect it is having trouble finding my "My Documents\My Games\Path of Exile" folder location as it is on a different drive. I tried by entering the **full** path drive such as:
filter=E:\My Documents\My Games\Path of Exile\POEQOL_Base.filter
Maybe adding a comment is a good idea? Example:
####### filter=E:\My Documents\My Games\Path of Exile\POEQOL_Base.filter

And it worked! The issue was mainly the lack of quotations. That is unusual and might cause issues.

Suggestions:
1. Implement quotations for file/folder location
2. Add a comment line in the setup to give users an explanation and example for full path 
3. Return a non-generic error if you don't find the file/folder location during installation/runtime

[https://i.imgur.com/B4MWp6u.png](url)

**Comment by rorshan** [comment]
Does your fix persist through re-launching the app? For me it only works for the first launch, I have to delete/re-copy the filter file to make it work again

**Comment by lucayde** [comment]
I am having the same error, "Failed to execute script POE_QOL2", however I doubt the cause is the same since I'm not using an external drive. I believe I have entered all the setup correctly so I have no idea what could be the cause.

**Comment by tmjones212** [comment]
I'm getting the same error, have everything on one drive.

**Comment by hellboychess** [comment]
Same problem. I did manage the program to work just once.
And another : I'm a french user, and it seems to be an issue with spelling (3map3 for "map"). num key is the same, but in french, " is normal character and 3 for capslock

**Comment by faeder** [comment]
I had a similar issue, my documents are stored on a OneDrive, this fixed the issue.

**Comment by notablackbear** [comment]
Thanks @LoneWolfHowl I'll add the note to the `Setup.ini` file. I don't plan on adding and more advanced error messaging until a couple weeks after league start atm.

To everyone else, please try the latest files. This is related to #4.
