### ISSUE TITLE
[Suggestion]the Chaos recipe item highlight

### ISSUE THREAD

**Issue by tBmo** [notablackbear/poe_qolV2#52]
First of all, thanks for such great tools to make all exiles lives much easier, I'm enjoying the tool when all of us are doing the Chaos recipe. If you don't mind, I have some suggestions after a short time period usage.

I happen to notice that the tool selects only the items between 60 and 74 in the tab for the recipe currently. But, I think that the recipe would work as long as, among all pieces of the a full set, one item with the lowest item level has the ilvl between 60 and 74. The tool currently is able to count how many weapons, helmets, and etc. are with ilvl 60 and 74 in tab. What I m thinking is that users could pick one type on the overlay, say body armors, then, when the tool start to highlight the full of set for the recipe, the tool could select the items except for body armors with ilvl even higher than 74. Even better, instead of having user to pick, the tool could pick the type based on the lowest or highest count among 8 types of items. Once the type with the lowest ilvl picked, the tool could select other pieces at the highest ilvl. 

Here is an example. Let's say there are 25 pairs of gloves wit ilvl 60 and 74 in the tab, and the other pieces at such ilvl are less than 25. Also, I have a couple of pair of boots, one at ilvl 75 and the other at ilvl 76. When i click "Chaos recipe" after glove is "pick" on the overlay, the tool would highlight a full set in the tab with choosing boots at ilvl 76 and ilvl 75 for the first batch.

**Comment by notablackbear** [comment]
>First of all, thanks for such great tools to make all exiles lives much easier, I'm enjoying the tool when all of us are doing the Chaos recipe. 

Thanks for the compliment. And im glad it works for you. These kinds of comments keep me going on this.

I absolutely agree with this. It would be a great feature and improve the efficiency of the player and the amount of Chaos Recipes they can complete. I've added this to the future plans list.
