### ISSUE TITLE
Bug in Auto-updating filter, resulting in crash on restart of app

### ISSUE THREAD

**Issue by MartinHoffmannJena** [notablackbear/poe_qolV2#6]
In the file POEQOL_Base.filter, at the end of the auto update section, these two lines exist:

Identified False
\# 2345ina8dsf7 End Chaos Recipe Auto-Update Section

If i close the tool, the file will get rewritten, but this time a linebreak is missing:

Identified False# 2345ina8dsf7 End Chaos Recipe Auto-Update Section

This is maybe a result of my Documents/My Games folder not being in the default location, but supplied with full path in the setup.ini

**Comment by MartinHoffmannJena** [comment]
As a hotfix you can add a linebreak at the end of the chaos_items_filter.filter file and it will work

**Comment by notablackbear** [comment]
Thanks @MartinHoffmannJena . The required linebreak has been added! Hopefully this can be re-written in a less error prone way in the future. I'll leave this issue open until then.
